version: "3"
services:
  springboot-app:
    container_name: spring-app
    build :
      context: .
    ports:
      - "9887:8083"

    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root@123
      MYSQL_PORT: 3306

  mysqldb:
    container_name : mysqldb
    image: mysql

    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=roo@123
      - MYSQL_DATABASE=students
      - MYSQL_PASSWORD=root@123
    ports:
      - "3307:3306"